const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const body=document.body,cfg=window.NS_CONFIG||{};
$('[data-year]')?.replaceChildren(document.createTextNode(new Date().getFullYear()));
const key=body.dataset.page;$$('.nav a').forEach(a=>a.dataset.key===key&&a.classList.add('active'));
const menu=$('[data-menu]'),nav=$('[data-nav]');
function closeMenu(){nav?.classList.remove('open');menu?.classList.remove('open');menu?.setAttribute('aria-expanded','false');menu?.setAttribute('aria-label','Open menu');body.classList.remove('lock')}
menu?.addEventListener('click',()=>{const o=nav.classList.toggle('open');menu.classList.toggle('open',o);menu.setAttribute('aria-expanded',String(o));menu.setAttribute('aria-label',o?'Close menu':'Open menu');body.classList.toggle('lock',o)});
$$('.nav a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;let obs=null;
if(reduceMotion){$$('.reveal').forEach(x=>x.classList.add('visible'))}else{obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(x=>obs.observe(x))}
const INSIGHTS=[{cat:'Development Basics',title:'What makes a site development-ready?',text:'A project starts with more than location. Title clarity, access, planning rules, market demand and realistic costs all matter.'},{cat:'Design',title:'Why daylight and ventilation matter',text:'Good homes are shaped by orientation, openings, depth and planning—not only finishes and elevation styling.'},{cat:'Construction',title:'Quality starts before concrete',text:'Drawings, specifications, quantities, procurement and supervision determine quality long before the finishing stage.'},{cat:'Real Estate',title:'Price is not the same as value',text:'Location, layout, maintenance, construction quality and long-term usability can matter more than a launch discount.'},{cat:'Planning',title:'Why feasibility comes before branding',text:'A strong project idea needs to work on area, cost, permissions, pricing and demand before a name or campaign matters.'},{cat:'Brand Journal',title:'Why N&S is building quietly first',text:'The goal is to build knowledge and standards now, then let future completed work become the real marketing.'}];
function card(x){return `<article class="insight-card reveal"><small>${x.cat}</small><h3>${x.title}</h3><p>${x.text}</p><span class="read">N&S NOTES · GENERAL EDUCATION</span></article>`}
function observeNew(c){if(reduceMotion)$$('.reveal',c).forEach(x=>x.classList.add('visible'));else $$('.reveal',c).forEach(x=>obs?.observe(x))}
const home=$('[data-insights-home]');if(home){home.innerHTML=INSIGHTS.slice(0,3).map(card).join('');observeNew(home)}
const all=$('[data-insights-all]');if(all){all.innerHTML=INSIGHTS.map(card).join('');observeNew(all)}
const emailLink=$('[data-email-link]'),emailLabel=$('[data-email-label]');if(cfg.email&&emailLink){emailLink.href=`mailto:${cfg.email}`;emailLink.classList.remove('disabled');emailLabel.textContent=cfg.email}
const form=$('[data-contact-form]');if(form){const submit=$('[data-submit-label]'),help=$('[data-form-help]'),status=$('[data-form-status]');if(cfg.formEndpoint){submit.textContent='Send message';help.textContent='Your message will be sent securely through the configured form service.'}form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const f=new FormData(form),msg=`Hello N&S DEVELOPERS,\n\nName: ${f.get('name')}\nContact: ${f.get('contact')}\nReason: ${f.get('reason')}\n\nMessage:\n${f.get('message')}`;if(cfg.formEndpoint){status?.classList.remove('hidden');if(status)status.textContent='Sending…';submit.disabled=true;try{const r=await fetch(cfg.formEndpoint,{method:'POST',headers:{Accept:'application/json'},body:f});if(!r.ok)throw new Error('send');if(status)status.textContent='Thank you. Your message has been sent.';form.reset()}catch{if(status)status.textContent='The message could not be sent. Please use email or Instagram instead.'}finally{submit.disabled=false}return}const wrap=$('[data-prepared-wrap]'),area=$('[data-prepared]');area.value=msg;wrap.classList.remove('hidden');const mail=$('[data-mail-message]');if(cfg.email){mail.href=`mailto:${cfg.email}?subject=${encodeURIComponent('Website introduction')}&body=${encodeURIComponent(msg)}`;mail.classList.remove('hidden')}wrap.scrollIntoView({behavior:reduceMotion?'auto':'smooth',block:'nearest'})})}
$('[data-copy-message]')?.addEventListener('click',async function(){const t=$('[data-prepared]').value;try{await navigator.clipboard.writeText(t);const old=this.textContent;this.textContent='Copied ✓';setTimeout(()=>this.textContent=old,1300)}catch{$('[data-prepared]').select();document.execCommand('copy')}});